Algoritmo "PG41i-par-impar"
// Disciplina   : Lógica de Programação
// Professor   : Jailson Costa dos Santos 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/09/2025
Var
   num: inteiro

Inicio
   Escreval("Digite um número inteiro: ")
   leia(num)

   se num mod 2 = 0 entao
      Escreval("O número é PAR")
   senao
      Escreval("O número é ÍMPAR")
   fimse
Fimalgoritmo
