Algoritmo "PG41k-maior3"
// Disciplina   : Lógica de Programação
// Professor   : Jailson Costa dos Santos 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gustavo Michel
// Data atual  : 26/09/2025
Var
   valor: inteiro

Inicio
   Escreval("Digite um número inteiro: ")
   leia(valor)

   se valor <= 3 entao
      Escreval("O valor informado foi: ", valor)
   fimse
Fimalgoritmo
