Algoritmo "PG46D-impares"
// Disciplina   : Lógica de Programação
// Professor    : Jailson Costa dos Santos
// Descrição    : Mostra números ímpares entre 0 e 20
// Autor(a)     : Gustavo Michel
// Data atual   : 26/09/2025
Var
   contador: inteiro

Inicio
   contador <- 0
   Enquanto contador <= 20 faca
      Se contador % 2 <> 0 entao
         Escreval(i)
      FimSe
      contador <- contador + 1
   FimEnquanto
Fimalgoritmo
