Algoritmo "PG66J-celsiusFahrenheit"
// Disciplina   : Lógica de Programação
// Professor    : Jailson Costa dos Santos
// Descrição    : Converte Celsius em Fahrenheit de 10 em 10 até 100
// Autor(a)     : Gustavo Michel
// Data atual   : 28/09/2025
Var
   celsius, fahrenheit: inteiro

Inicio
   Para celsius de 10 ate 100 passo 10 faca
      fahrenheit <- (celsius * 9 / 5) + 32
      Escreval(celsius, " °C = ", fahrenheit, " °F")
   FimPara
Fimalgoritmo