Algoritmo "PG66A-quadrados"
// Disciplina   : Lógica de Programação
// Professor    : Jailson Costa dos Santos
// Descrição    : Apresenta os quadrados dos números de 15 até 200
// Autor(a)     : Gustavo Michel
// Data atual   : 28/09/2025
Var
   contador, quadrado: inteiro

Inicio
   Para contador de 15 ate 200 faca
      quadrado <- contador * contador
      Escreval(contador, " ^ 2 = ", quadrado)
   FimPara
Fimalgoritmo
