Algoritmo "PG66C-soma100"
// Disciplina   : Lógica de Programação
// Professor    : Jailson Costa dos Santos
// Descrição    : Soma dos 100 primeiros números inteiros
// Autor(a)     : Gustavo Michel
// Data atual   : 28/09/2025
Var
   contador, soma: inteiro

Inicio
   soma <- 0
   Para contador de 1 ate 100 faca
      soma <- soma + contador
   FimPara

   Escreval("A soma dos 100 primeiros números é: ", soma)
Fimalgoritmo
